### ISSUE TITLE
Use Milestones instead of handrolling a Changelog

### ISSUE THREAD

**Issue by shicholas** [NeonLaw/codebase#1968]
## Describe the Feature

Instead of a Changelog, we can use GitHub Milestones to link Issues and PRs that correspond to a versioned release. With this change, our changelog can just be a regular markdown list linking to each Milestone.

## Packages

This feature affects

- Git Flow

## For the Assignee

- [ ] Create a branch or branches prefixed `feature/` that solves the issue
  above.
- [ ] Add this issue to one or more CHANGELOG files
- [ ] Verify this is fully deployed on Staging and comment on this issue with
  the commit or PR.
- [ ] Verify this is fully deployed on Prodcution and comment on this issue with
  the commit or PR.

**Comment by shicholas** [comment]
This issue is stale because it has been open 30 days with no
activity. Remove stale label or comment or this will be closed in
30 days.
